const excelWeb='https://jmartins.sharepoint.com/:x:/r/sites/EntrenamientoR3/_layouts/15/Doc.aspx?sourcedoc=%7BB762772B-6048-4002-AF66-F0BC9A0A1055%7D&file=Ingresos%20con%20tiendas%20de%20entrenamiento%20y%20pares%20formadores.xlsm&action=default&mobileredirect=true';
function abrirExcel(){location.href='ms-excel:ofe|u|'+excelWeb}

let arandoRecords=[];
let interviewRecords=[];
let agendaRecords=[];
let calendarCursor=null;
const loadedFlags={agenda:false,arando:false,interview:false};
const CACHE_DB='PortalJDZ_Data_v2';
const CACHE_STORE='datasets';

function norm(v){return String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim().toLowerCase()}
function safe(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function statusClass(v){const x=norm(v);if(x.includes('no aprobado')||x.includes('no aprueba')||x.includes('cancel')||x.includes('no apto'))return'bad';if(x.includes('aprobado')||x.includes('aprueba')||x.includes('realizado')||x.includes('complet'))return'ok';if(x.includes('pend')||x.includes('proceso')||x.includes('evalu'))return'warn';return'info'}
function dateDisplay(iso){if(!iso)return'';const p=String(iso).split('-');return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:iso}
function isoDate(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function startOfWeek(d){const x=new Date(d);const day=x.getDay();const diff=day===0?-6:1-day;x.setDate(x.getDate()+diff);x.setHours(12,0,0,0);return x}

function openCache(){return new Promise((resolve,reject)=>{const req=indexedDB.open(CACHE_DB,1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(CACHE_STORE))db.createObjectStore(CACHE_STORE,{keyPath:'key'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function cacheGet(key){const db=await openCache();return new Promise((resolve,reject)=>{const tx=db.transaction(CACHE_STORE,'readonly');const req=tx.objectStore(CACHE_STORE).get(key);req.onsuccess=()=>{db.close();resolve(req.result||null)};req.onerror=()=>{db.close();reject(req.error)}})}
function markLoaded(key){loadedFlags[key]=true;const el=document.getElementById('kpiSources');if(el)el.textContent=Object.values(loadedFlags).filter(Boolean).length}

function applyArandoData(records){arandoRecords=records||[];const k=document.getElementById('kpiArando');if(k)k.textContent=arandoRecords.length;if(arandoRecords.length)markLoaded('arando');const out=document.getElementById('sapResult');if(out)out.innerHTML=arandoRecords.length?'<div class="empty-state">Datos listos. Escribe un SAP para consultar el historial.</div>':'<div class="empty-state">No hay una fuente de Arando cargada en este navegador.</div>'}
function buscarSAP(){const sap=document.getElementById('sap').value.trim();const out=document.getElementById('sapResult');if(!arandoRecords.length){out.innerHTML='<div class="empty-state">No hay datos de Arando cargados.</div>';return}if(!sap){out.innerHTML='<div class="empty-state">Escribe un SAP para consultar.</div>';return}const rows=arandoRecords.filter(r=>String(r.sap)===sap);if(!rows.length){out.innerHTML=`<div class="empty-state">No se encontraron registros para el SAP <b>${safe(sap)}</b>.</div>`;return}out.innerHTML='<table><thead><tr><th>SAP</th><th>Nombre</th><th>Tipo</th><th>Grupo</th><th>Concepto</th><th>Nuevo cargo</th></tr></thead><tbody>'+rows.map(r=>`<tr><td>${safe(r.sap)}</td><td>${safe(r.nombre)}</td><td>${safe(r.tipo)}</td><td>${safe(r.grupo)}</td><td><span class="status ${statusClass(r.concepto)}">${safe(r.concepto||'Sin concepto')}</span></td><td>${safe(r.nuevo||'-')}</td></tr>`).join('')+'</tbody></table>'}

function applyInterviewData(records){interviewRecords=records||[];const k=document.getElementById('kpiInterview');if(k)k.textContent=interviewRecords.length;if(interviewRecords.length)markLoaded('interview');renderInterviewRows(interviewRecords.slice(0,8))}
function renderInterviewRows(rows){const body=document.querySelector('#it tbody');if(!body)return;if(!rows.length){body.innerHTML='<tr><td colspan="7" class="empty-cell">Sin resultados</td></tr>';return}body.innerHTML=rows.map(r=>`<tr><td>${safe(r.sap)}</td><td>${safe(r.nombre)}</td><td>${safe(r.cargoActual||'-')}</td><td>${safe(r.cargoAspira||'-')}</td><td>${safe(dateDisplay(r.fecha)||'-')}</td><td>${safe(r.hora||'-')}</td><td><span class="status ${statusClass(r.concepto||r.estado)}">${safe(r.concepto||r.estado||'Pendiente')}</span></td></tr>`).join('')}
function filtrarEntrevistas(){if(!interviewRecords.length){renderInterviewRows([]);return}const q=norm(document.getElementById('iText')?.value),date=document.getElementById('iDate')?.value||'';const rows=interviewRecords.filter(r=>(!q||norm(r.sap+' '+r.nombre).includes(q))&&(!date||r.fecha===date));renderInterviewRows(rows.slice(0,50))}

function applyAgendaData(records){agendaRecords=(records||[]).slice().sort((a,b)=>String(a.fecha).localeCompare(String(b.fecha))||String(a.actividad).localeCompare(String(b.actividad)));const k=document.getElementById('kpiAgenda');if(k)k.textContent=agendaRecords.length;if(agendaRecords.length){markLoaded('agenda');calendarCursor=startOfWeek(new Date(agendaRecords[agendaRecords.length-1].fecha+'T12:00:00'));renderAgendaWeek()}else renderAgendaWeek()}
function classifyEvent(t){const x=norm(t);if(x.includes('arando'))return'evt-purple';if(x.includes('aula'))return'evt-blue';if(x.includes('circuit'))return'evt-pink';if(x.includes('bienvenida')||x.includes('onboarding'))return'evt-green';if(x.includes('timesoft'))return'evt-yellow';if(x.includes('reunion'))return'evt-orange';return'evt-gray'}
function moveWeek(n){if(!calendarCursor)calendarCursor=startOfWeek(new Date());calendarCursor=addDays(calendarCursor,7*n);renderAgendaWeek()}
function goToday(){calendarCursor=startOfWeek(new Date());renderAgendaWeek()}
function goLatest(){if(!agendaRecords.length)return;calendarCursor=startOfWeek(new Date(agendaRecords[agendaRecords.length-1].fecha+'T12:00:00'));renderAgendaWeek()}
function renderAgendaWeek(){const wrap=document.getElementById('calendarView');if(!wrap)return;if(!agendaRecords.length){wrap.innerHTML='<div class="empty-state agenda-empty">No hay una agenda cargada en este navegador.</div>';const t=document.getElementById('calendarPeriod');if(t)t.textContent='';return}if(!calendarCursor)calendarCursor=startOfWeek(new Date(agendaRecords[agendaRecords.length-1].fecha+'T12:00:00'));const labels=['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'];let html='<div class="agenda-week">';for(let i=0;i<7;i++){const d=addDays(calendarCursor,i),iso=isoDate(d),events=agendaRecords.filter(e=>e.fecha===iso);html+=`<div class="agenda-day"><div class="agenda-day-head"><b>${labels[i]} ${d.getDate()}</b><span>${d.toLocaleDateString('es-CO',{month:'short'})}</span></div><div class="agenda-day-body">${events.length?events.map(e=>`<div class="agenda-event ${e.tipo||classifyEvent(e.actividad)}"><b>${safe(e.actividad).split(' / ').join('<br>')}</b><span>Actividad del calendario de entrenamiento</span></div>`).join(''):'<div class="no-event">Sin programación</div>'}</div></div>`}html+='</div>';wrap.innerHTML=html;const title=document.getElementById('calendarPeriod');if(title){const end=addDays(calendarCursor,6);title.textContent=`${calendarCursor.getDate()} ${calendarCursor.toLocaleDateString('es-CO',{month:'short'})} – ${end.getDate()} ${end.toLocaleDateString('es-CO',{month:'short'})} ${end.getFullYear()}`}}

async function restoreCachedData(){try{const [a,i,g]=await Promise.all([cacheGet('arando'),cacheGet('interview'),cacheGet('agenda')]);applyArandoData(a?.records||[]);applyInterviewData(i?.records||[]);applyAgendaData(g?.records||[])}catch(e){console.warn('No se pudo restaurar la información guardada:',e)}}

document.getElementById('globalSearch')?.addEventListener('input',e=>{const q=norm(e.target.value);document.querySelectorAll('.searchable').forEach(x=>x.classList.toggle('hidden',q&&!norm((x.dataset.search||'')+' '+x.innerText).includes(q)))})
document.getElementById('sap')?.addEventListener('keydown',e=>{if(e.key==='Enter')buscarSAP()});
restoreCachedData();